databases:
  - name: django.db.backends.postgresql
    plan: free
    databaseName: dj_test
    user: postgres

services:
  - type: web
    plan: free
    name: simR
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn simR.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django.db.backends.postgresql
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4